version: '3.9'
services:
  elasticsearch:
    image: elasticsearch:7.12.0
    volumes:
      - ./config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
    expose:
      - 9200
    ports:
      - "9200:9200"
    container_name: elastic
    networks:
      localnt:
        aliases:
          - elastic

  postgres:
    image: postgres:13.2
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=postgres
    ports:
      - "5432:5432"
    container_name: postgres
    networks:
      localnt:
        aliases:
          - postgres

  minio:
    image: minio/minio:RELEASE.2021-01-30T00-20-58Z.hotfix.0c1d75aa8
    volumes:
      - /tmp/data:/data
    expose:
      - "9000"
    ports:
      - "9000:9000"
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: minio123
    command: server --address 0.0.0.0:9000 /data
    container_name: minio
    networks:
      localnt:
        aliases:
          - minio

networks:
  localnt: { }